<Project>
    <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!-- Avalonia packages -->
        <PackageVersion Include="Avalonia" Version="12.1.2" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageVersion Include="Avalonia.Android" Version="12.1.2" />
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageVersion Include="OfficeIMO.Excel.Html" Version="3.3.0" />
        <PackageVersion Include="OfficeIMO.PowerPoint" Version="3.3.0" />
        <PackageVersion Include="OfficeIMO.Word.Html" Version="3.3.0" />
    </ItemGroup>
</Project>
