<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ApplicationId>net.drabc.survoler</ApplicationId>
    <ApplicationDisplayVersion>$(VersionPrefix)</ApplicationDisplayVersion>
    <ApplicationVersion Condition="'$(_SurvolerVersionValid)' == 'True'">$([MSBuild]::Add($([MSBuild]::Add($([MSBuild]::Multiply($([System.Version]::Parse('$(VersionPrefix)').Major), 1000000)), $([MSBuild]::Multiply($([System.Version]::Parse('$(VersionPrefix)').Minor), 1000)))), $([MSBuild]::Add($([System.Version]::Parse('$(VersionPrefix)').Build), 1))))</ApplicationVersion>
    <AndroidPackageFormats>apk</AndroidPackageFormats>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Survoler\Survoler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Include="..\Survoler\Assets\icon.png"
                     Link="Resources\mipmap\survoler_icon.png" />
    <AndroidResource Include="..\Survoler\Assets\icon_trans.png"
                     Link="Resources\drawable-nodpi\survoler_icon_foreground_source.png" />
  </ItemGroup>
</Project>
